version: "3.9"

networks:
  postgres_network:
    driver: bridge

volumes:
  primary_data:
  archive_data:

services:

  primary:
    container_name: primary_container
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ./config/primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./migrations/volumes_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/create_replica_user.sh:/docker-entrypoint-initdb.d/01_create_replica_user.sh
      - primary_data:/var/lib/postgresql/data
      - archive_data:/var/lib/postgresql/archive
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
